jobs:
  include:
    - stage: test
      name: Docker

      services:
        - docker

      install:
        - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        - unzip terraform_0.12.24_linux_amd64.zip -d /tmp
        - sudo mv /tmp/terraform /usr/local/bin/

      script:
        - docker/tests/setup.sh && docker/tests/suite.sh
        - docker/tests/cleanup.sh

      addons:
        hosts:
          - alias.localhost
          - finance.localhost
          - library.localhost
          - news.localhost
          - notes.localhost
          - sync.notes.localhost
          - tasks.localhost
